apiVersion: apps/v1
kind: Deployment
metadata: 
    name: web_app
spec:
    selector:
      matchLabels:
        app: web
    template:
      metadata:
        labels:
          app: web
      spec:
        containers:
        - name: kube
          image: docker.io/shreyas1717/kube:
          ports:
          - containerPort: 80
            hostPort: 8081
