apiVersion: apps/v1
kind: Deployment
metadata: 
    name: web-app
spec:
    selector:
      matchLabels:
        app: web
    template:
      metadata:
        labels:
          app: web
      spec:
        containers:
        - name: kube-app
          image: docker.io/shreyas1717/web_app:latest
          ports:
          - containerPort: 80
            hostPort: 8081
